+--------+-----------+--------------------------------------------------+-------------------------------------+---------------------------------------------------------------+----------------------------+
| Domain | Method    | URI                                              | Name                                | Action                                                        | Middleware                 |
+--------+-----------+--------------------------------------------------+-------------------------------------+---------------------------------------------------------------+----------------------------+
|        | GET|HEAD  | /                                                |                                     | Closure                                                       | web                        |
|        | GET|HEAD  | admin                                            |                                     | App\Admin\Controllers\HomeController@index                    | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/auth/login                                 |                                     | App\Admin\Controllers\AuthController@getLogin                 | admin.app:admin,web,admin  |
|        | POST      | admin/auth/login                                 |                                     | App\Admin\Controllers\AuthController@postLogin                | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/auth/logout                                |                                     | App\Admin\Controllers\AuthController@getLogout                | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/auth/logs                                  | logs.index                          | Dcat\Admin\Controllers\LogController@index                    | admin.app:admin,web,admin  |
|        | DELETE    | admin/auth/logs/{log}                            | logs.destroy                        | Dcat\Admin\Controllers\LogController@destroy                  | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/auth/menu                                  | menu.index                          | Dcat\Admin\Controllers\MenuController@index                   | admin.app:admin,web,admin  |
|        | POST      | admin/auth/menu                                  | menu.store                          | Dcat\Admin\Controllers\MenuController@store                   | admin.app:admin,web,admin  |
|        | PUT|PATCH | admin/auth/menu/{menu}                           | menu.update                         | Dcat\Admin\Controllers\MenuController@update                  | admin.app:admin,web,admin  |
|        | DELETE    | admin/auth/menu/{menu}                           | menu.destroy                        | Dcat\Admin\Controllers\MenuController@destroy                 | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/auth/menu/{menu}/edit                      | menu.edit                           | Dcat\Admin\Controllers\MenuController@edit                    | admin.app:admin,web,admin  |
|        | POST      | admin/auth/permissions                           | permissions.store                   | Dcat\Admin\Controllers\PermissionController@store             | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/auth/permissions                           | permissions.index                   | Dcat\Admin\Controllers\PermissionController@index             | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/auth/permissions/create                    | permissions.create                  | Dcat\Admin\Controllers\PermissionController@create            | admin.app:admin,web,admin  |
|        | DELETE    | admin/auth/permissions/{permission}              | permissions.destroy                 | Dcat\Admin\Controllers\PermissionController@destroy           | admin.app:admin,web,admin  |
|        | PUT|PATCH | admin/auth/permissions/{permission}              | permissions.update                  | Dcat\Admin\Controllers\PermissionController@update            | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/auth/permissions/{permission}              | permissions.show                    | Dcat\Admin\Controllers\PermissionController@show              | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/auth/permissions/{permission}/edit         | permissions.edit                    | Dcat\Admin\Controllers\PermissionController@edit              | admin.app:admin,web,admin  |
|        | POST      | admin/auth/roles                                 | roles.store                         | Dcat\Admin\Controllers\RoleController@store                   | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/auth/roles                                 | roles.index                         | Dcat\Admin\Controllers\RoleController@index                   | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/auth/roles/create                          | roles.create                        | Dcat\Admin\Controllers\RoleController@create                  | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/auth/roles/{role}                          | roles.show                          | Dcat\Admin\Controllers\RoleController@show                    | admin.app:admin,web,admin  |
|        | PUT|PATCH | admin/auth/roles/{role}                          | roles.update                        | Dcat\Admin\Controllers\RoleController@update                  | admin.app:admin,web,admin  |
|        | DELETE    | admin/auth/roles/{role}                          | roles.destroy                       | Dcat\Admin\Controllers\RoleController@destroy                 | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/auth/roles/{role}/edit                     | roles.edit                          | Dcat\Admin\Controllers\RoleController@edit                    | admin.app:admin,web,admin  |
|        | PUT       | admin/auth/setting                               |                                     | App\Admin\Controllers\AuthController@putSetting               | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/auth/setting                               |                                     | App\Admin\Controllers\AuthController@getSetting               | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/auth/users                                 | users.index                         | Dcat\Admin\Controllers\UserController@index                   | admin.app:admin,web,admin  |
|        | POST      | admin/auth/users                                 | users.store                         | Dcat\Admin\Controllers\UserController@store                   | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/auth/users/create                          | users.create                        | Dcat\Admin\Controllers\UserController@create                  | admin.app:admin,web,admin  |
|        | DELETE    | admin/auth/users/{user}                          | users.destroy                       | Dcat\Admin\Controllers\UserController@destroy                 | admin.app:admin,web,admin  |
|        | PUT|PATCH | admin/auth/users/{user}                          | users.update                        | Dcat\Admin\Controllers\UserController@update                  | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/auth/users/{user}                          | users.show                          | Dcat\Admin\Controllers\UserController@show                    | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/auth/users/{user}/edit                     | users.edit                          | Dcat\Admin\Controllers\UserController@edit                    | admin.app:admin,web,admin  |
|        | POST      | admin/dcat-api/action                            | dcat.api.admin.action               | Dcat\Admin\Controllers\HandleActionController@handle          | web,admin                  |
|        | POST      | admin/dcat-api/editor-md/upload                  | dcat.api.admin.editor-md.upload     | Dcat\Admin\Controllers\EditorMDController@upload              | web,admin                  |
|        | POST      | admin/dcat-api/form                              | dcat.api.admin.form                 | Dcat\Admin\Controllers\HandleFormController@handle            | web,admin                  |
|        | POST      | admin/dcat-api/tinymce/upload                    | dcat.api.admin.tinymce.upload       | Dcat\Admin\Controllers\TinymceController@upload               | web,admin                  |
|        | POST      | admin/dcat-api/value                             | dcat.api.admin.value                | Dcat\Admin\Controllers\ValueController@handle                 | web,admin                  |
|        | GET|HEAD  | admin/helpers/extensions                         | extensions.index                    | Dcat\Admin\Controllers\ExtensionController@index              | admin.app:admin,web,admin  |
|        | POST      | admin/helpers/extensions                         | extensions.store                    | Dcat\Admin\Controllers\ExtensionController@store              | admin.app:admin,web,admin  |
|        | POST      | admin/helpers/extensions/import                  |                                     | Dcat\Admin\Controllers\ExtensionController@import             | admin.app:admin,web,admin  |
|        | PUT|PATCH | admin/helpers/extensions/{extension}             | extensions.update                   | Dcat\Admin\Controllers\ExtensionController@update             | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/helpers/icons                              |                                     | Dcat\Admin\Controllers\IconController@index                   | admin.app:admin,web,admin  |
|        | POST      | admin/helpers/scaffold                           |                                     | Dcat\Admin\Controllers\ScaffoldController@store               | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/helpers/scaffold                           |                                     | Dcat\Admin\Controllers\ScaffoldController@index               | admin.app:admin,web,admin  |
|        | POST      | admin/helpers/scaffold/table                     |                                     | Dcat\Admin\Controllers\ScaffoldController@table               | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/img-videos                                 | img-videos.index                    | App\Admin\Controllers\ImgVideosController@index               | admin.app:admin,web,admin  |
|        | POST      | admin/img-videos                                 | img-videos.store                    | App\Admin\Controllers\ImgVideosController@store               | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/img-videos/create                          | img-videos.create                   | App\Admin\Controllers\ImgVideosController@create              | admin.app:admin,web,admin  |
|        | PUT|PATCH | admin/img-videos/{img_video}                     | img-videos.update                   | App\Admin\Controllers\ImgVideosController@update              | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/img-videos/{img_video}                     | img-videos.show                     | App\Admin\Controllers\ImgVideosController@show                | admin.app:admin,web,admin  |
|        | DELETE    | admin/img-videos/{img_video}                     | img-videos.destroy                  | App\Admin\Controllers\ImgVideosController@destroy             | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/img-videos/{img_video}/edit                | img-videos.edit                     | App\Admin\Controllers\ImgVideosController@edit                | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/jinzhu-users                               | jinzhu-users.index                  | App\Admin\Controllers\JinzhuUsersController@index             | admin.app:admin,web,admin  |
|        | POST      | admin/jinzhu-users                               | jinzhu-users.store                  | App\Admin\Controllers\JinzhuUsersController@store             | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/jinzhu-users/create                        | jinzhu-users.create                 | App\Admin\Controllers\JinzhuUsersController@create            | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/jinzhu-users/{jinzhu_user}                 | jinzhu-users.show                   | App\Admin\Controllers\JinzhuUsersController@show              | admin.app:admin,web,admin  |
|        | PUT|PATCH | admin/jinzhu-users/{jinzhu_user}                 | jinzhu-users.update                 | App\Admin\Controllers\JinzhuUsersController@update            | admin.app:admin,web,admin  |
|        | DELETE    | admin/jinzhu-users/{jinzhu_user}                 | jinzhu-users.destroy                | App\Admin\Controllers\JinzhuUsersController@destroy           | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/jinzhu-users/{jinzhu_user}/edit            | jinzhu-users.edit                   | App\Admin\Controllers\JinzhuUsersController@edit              | admin.app:admin,web,admin  |
|        | POST      | admin/users                                      | users.store                         | App\Admin\Controllers\UsersController@store                   | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/users                                      | users.index                         | App\Admin\Controllers\UsersController@index                   | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/users/create                               | users.create                        | App\Admin\Controllers\UsersController@create                  | admin.app:admin,web,admin  |
|        | DELETE    | admin/users/{user}                               | users.destroy                       | App\Admin\Controllers\UsersController@destroy                 | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/users/{user}                               | users.show                          | App\Admin\Controllers\UsersController@show                    | admin.app:admin,web,admin  |
|        | PUT|PATCH | admin/users/{user}                               | users.update                        | App\Admin\Controllers\UsersController@update                  | admin.app:admin,web,admin  |
|        | GET|HEAD  | admin/users/{user}/edit                          | users.edit                          | App\Admin\Controllers\UsersController@edit                    | admin.app:admin,web,admin  |
|        | GET|HEAD  | api/user                                         |                                     | Closure                                                       | api,auth:api               |
|        | POST      | api/v1/authorizations                            | api.v1.api.authorizations.store     | App\Http\Controllers\Api\AuthorizationsController@store       | api,throttle:60,1          |
|        | DELETE    | api/v1/authorizations/current                    | api.v1.authorizations.destroy       | App\Http\Controllers\Api\AuthorizationsController@destroy     | api,throttle:10,1          |
|        | PUT       | api/v1/authorizations/current                    | api.v1.authorizations.update        | App\Http\Controllers\Api\AuthorizationsController@update      | api,throttle:10,1          |
|        | POST      | api/v1/avatars                                   | api.v1.avatars.store                | App\Http\Controllers\Api\AvatarsController@store              | api,throttle:60,1,auth:api |
|        | POST      | api/v1/captchas                                  | api.v1.captchas.store               | App\Http\Controllers\Api\CaptchasController@store             | api,throttle:10,1          |
|        | POST      | api/v1/collection-ms-img-videos                  | api.v1.img-videos.collection        | App\Http\Controllers\Api\ImgVideosController@collection       | api,throttle:60,1,auth:api |
|        | GET|HEAD  | api/v1/img-videos                                | api.v1.img-videos.index             | App\Http\Controllers\Api\ImgVideosController@index            | api,throttle:60,1,auth:api |
|        | POST      | api/v1/img-videos                                | api.v1.img-videos.store             | App\Http\Controllers\Api\ImgVideosController@store            | api,throttle:60,1,auth:api |
|        | GET|HEAD  | api/v1/img-videos/{img_video}                    | api.v1.img-videos.show              | App\Http\Controllers\Api\ImgVideosController@show             | api,throttle:60,1,auth:api |
|        | PUT|PATCH | api/v1/img-videos/{img_video}                    | api.v1.img-videos.update            | App\Http\Controllers\Api\ImgVideosController@update           | api,throttle:60,1,auth:api |
|        | DELETE    | api/v1/img-videos/{img_video}                    | api.v1.img-videos.destroy           | App\Http\Controllers\Api\ImgVideosController@destroy          | api,throttle:60,1,auth:api |
|        | POST      | api/v1/installments                              | api.v1.installments.store           | App\Http\Controllers\Api\InstallmentsController@store         | api,throttle:60,1,auth:api |
|        | PUT|PATCH | api/v1/installments/{installment}                | api.v1.installments.update          | App\Http\Controllers\Api\InstallmentsController@update        | api,throttle:60,1,auth:api |
|        | DELETE    | api/v1/installments/{installment}                | api.v1.installments.destroy         | App\Http\Controllers\Api\InstallmentsController@destroy       | api,throttle:60,1,auth:api |
|        | GET|HEAD  | api/v1/installments/{installment}                | api.v1.installments.show            | App\Http\Controllers\Api\InstallmentsController@show          | api,throttle:60,1,auth:api |
|        | GET|HEAD  | api/v1/ms-img-videos/{user}                      | api.v1.img-videos.msindex           | App\Http\Controllers\Api\ImgVideosController@msindex          | api,throttle:60,1,auth:api |
|        | POST      | api/v1/ms-publishes                              | api.v1.ms-publishes.store           | App\Http\Controllers\Api\MsPublishesController@store          | api,throttle:60,1,auth:api |
|        | GET|HEAD  | api/v1/ms-publishes                              | api.v1.ms-publishes.index           | App\Http\Controllers\Api\MsPublishesController@index          | api,throttle:60,1,auth:api |
|        | GET|HEAD  | api/v1/ms-publishes/{ms_publish}                 | api.v1.ms-publishes.show            | App\Http\Controllers\Api\MsPublishesController@show           | api,throttle:60,1,auth:api |
|        | PUT|PATCH | api/v1/ms-publishes/{ms_publish}                 | api.v1.ms-publishes.update          | App\Http\Controllers\Api\MsPublishesController@update         | api,throttle:60,1,auth:api |
|        | DELETE    | api/v1/ms-publishes/{ms_publish}                 | api.v1.ms-publishes.destroy         | App\Http\Controllers\Api\MsPublishesController@destroy        | api,throttle:60,1,auth:api |
|        | POST      | api/v1/ms-traffic-infos                          | api.v1.ms-traffic-infos.store       | App\Http\Controllers\Api\MsTrafficInfosController@store       | api,throttle:60,1,auth:api |
|        | DELETE    | api/v1/ms-traffic-infos/{ms_traffic_info}        | api.v1.ms-traffic-infos.destroy     | App\Http\Controllers\Api\MsTrafficInfosController@destroy     | api,throttle:60,1,auth:api |
|        | PUT|PATCH | api/v1/ms-traffic-infos/{ms_traffic_info}        | api.v1.ms-traffic-infos.update      | App\Http\Controllers\Api\MsTrafficInfosController@update      | api,throttle:60,1,auth:api |
|        | GET|HEAD  | api/v1/ms-traffic-infos/{ms_traffic_info}        | api.v1.ms-traffic-infos.show        | App\Http\Controllers\Api\MsTrafficInfosController@show        | api,throttle:60,1,auth:api |
|        | POST      | api/v1/socials/{social_type}/authorizations      | api.v1.socials.authorizations.store | App\Http\Controllers\Api\AuthorizationsController@socialStore | api,throttle:10,1          |
|        | DELETE    | api/v1/uncollection-ms-img-videos/{img_video_id} | api.v1.img-videos.uncollection      | App\Http\Controllers\Api\ImgVideosController@uncollection     | api,throttle:60,1,auth:api |
|        | PATCH     | api/v1/user                                      | api.v1.user.update                  | App\Http\Controllers\Api\UsersController@update               | api,throttle:60,1,auth:api |
|        | GET|HEAD  | api/v1/user                                      | api.v1.user.show                    | App\Http\Controllers\Api\UsersController@me                   | api,throttle:60,1,auth:api |
|        | POST      | api/v1/users                                     | api.v1.users.store                  | App\Http\Controllers\Api\UsersController@store                | api,throttle:10,1          |
|        | GET|HEAD  | api/v1/users/{user}                              | api.v1.users.show                   | App\Http\Controllers\Api\UsersController@show                 | api,throttle:60,1,auth:api |
|        | POST      | api/v1/verificationCodes                         | api.v1.verificationCodes.store      | App\Http\Controllers\Api\VerificationCodesController@store    | api,throttle:10,1          |
+--------+-----------+--------------------------------------------------+-------------------------------------+---------------------------------------------------------------+----------------------------+
vagrant@homestead:~/code/2020work/jinquan$
